.TH GAKE 6 2021-11-06 "Blue-Maned_Hawk" "Gake Reference Manual"
.SH NAME
gake \- an open-source reimplementation of Google's snake game, with extensions.
.SH SYNOPSIS
.B gake
[
.B -v?h
]
.SH CONFIGURATION
Gake does not currently have any configuration features.  In the future, a config file may be located in $XDG_CONFIG_HOME/Gake/ (or $HOME/.config/Gake).
.SH DESCRIPTION
Gake isn't currently anything.  In the future, it will be an open-source reimplementation of Google Snake, with some extensions.
.SH OPTIONS
.TP
.BR \-v
Displays the version of the program, then exits.
.TP
.BR \-h ", " \-?
Displays a blurb of help, then exits.
.SH EXIT STATUS
Gake returns a 0 if everything went fine.  Gake returns a 1 when used with \-v or \-?, for compatibility with other programs.

If Gake crashes, it will return a value ≥2, and will invoke a crash handler that will create an SDL messagebox giving a bit more explanation of the problem.  Currently, the exit codes are:
.IP
0x02:  User attempted to start the program with GNU-style options.
.SH ENVIRONMENT
The XDG environmental variables will probably be used by Gake, if they are set.
.SH FILES
Gake is installed into
.B /usr/local/bin/gake
and
.B /usr/local/share/Gake/Assets/
is where the assets are installed.
.SH BUGS
All bugs should be reported on the GitHub page for the project:
.I https://github.com/BlueManedHawk/Gake
