.TH GAKE 6 2021-11-06 "Blue-Maned_Hawk" "Gake Reference Manual"
.SH NAME
gake \- an open-source reimplementation of Google's snake game, with extensions.
.SH SYNOPSIS
.B gake
.SH CONFIGURATION
Gake does not currently have any configuration features.  In the future, a config file may be located in $XDG_CONFIG_HOME/Gake/ (or $HOME/.config/Gake).
.SH DESCRIPTION
Gake isn't currently anything.  In the future, it will be an open-source reimplementation of Google Snake, with some extensions.
.SH OPTIONS
Gake does not currently support any command-line options, but it will in the future.  None of these options will be GNU-Style options.
.SH EXIT STATUS
Gake will exit with a 0 code if everything went fine.  If it crashes, it will exit with a nonzero exit code based on what caused the crash.
.SH ENVIRONMENT
The XDG environmental variables will probably be used by Gake, if they are set.
.SH FILES
Gake is installed into
.B /usr/local/bin/gake
and
.B /usr/local/share/Gake/Assets/
is where the assets are installed.
.SH BUGS
All bugs should be reported on the GitHub page for the project:
.I https://github.com/BlueManedHawk/Gake
