.TH GAKE\-API 7 2022-01-08 "Blue-Maned_Hawk" "Gake Reference Manual"
.SH NAME
gake-api \- an overview of the API for Gake
.SH SYNOPSIS
In your program, write:
.RS 8
.TQ
.B include """gake.h"""
.TQ
.B struct gake_newstate gake_main(struct gake_curstate state);
.RE
.PP
Then, compile:
.IP
.BI "cc -shared " "Your.c Files.c Here.c" " -o" " Whatever.so"
.PP
Then, run:
.IP
.BI "gake -l " "Whatever.so"
.SH DESCRIPTION
Gake was primarily designed as a tool to determine algorithmic solutions to various extensions to the basic game of Snake.  The API of Gake will allow anyone to construct their own solutions to the problems, although currently, there's nothing in the game for the programs to interact with.
.PP
To write a program using the Gake API, you need to create a C file with a subroutine
.I gake_main()
in it;  this subroutine must accept a structure
.I gake_curstate
as its sole argument and return a structure
.IR gake_newstate .
These structures are defined in the header
.IR gake.h ,
or you could define them yourself.  (Languages besides C might be supported in the future.)
.PP
The structures contain the following members:
.PP
.B struct gake_curstate {
.RS 8
.TQ
.B long long frame;
.TQ
.B const char keys[];
.RE
.B }
.PP
.B struct gake_newstate {
.RS 8
.TQ
.B int dummy;
.RE
.B }
.PP
Your subroutine will be called after the game has handled input and updated the grid accordingly, but before it has rendered to the screen.
.PP
The structure you recieve will contain a long long stating how many frames have passed, and a string containing all of the keys pressed that frame.  Your program may use this information however it wishes.
.SH REPORTING BUGS
All bugs should be reported on the GitHub page for the project:
.UR
.I https://github.com/BlueManedHawk/Gake
.UE
.SH COPYRIGHT
This API is Copyright © 2021, 2022 Blue-Maned_Hawk;
.B however, programs that you make using the API are entirely your own.
However, I strongly encourage you to copyleft them, as I have done with this API.  Full licensing information is available in the LICENSE file that should have been supplied with this software).  This manpage is under the same license as described there.
.SH SEE ALSO
.B gake(6)
