.TH GAKE\-INTERNALS 7 2022-01-16 "Blue-Maned_Hawk" "Gake Reference Manual"
.SH NAME
gake-internals \- an overview of some internal things about Gake and its API
.SH SYNOPSIS
.B IMPORTANT:  This manpage is intended for developers of Gake and its API, not general users or those using the API.

This manpage documents some of the internal details of certain parts of Gake.  Currently, this is just the way that messages are sent via the FIFO between Gake and its API.
.SH DESCRIPTION
.SS The FIFO
A message through the FIFO consists of a header byte, followed by a payload byte.  If the header byte has its most significant bit set, the message is from Gake; otherwise, it's from the API.  Here's what each of the header bytes means.
.IP 0x00:
This begins a message to be logged.  The payload is the first character of the message.
.IP 0x01:
This continues a log message.  The payload is another character of the message.
.IP 0x02:
This stops the message portion of the log message.  The payload is the final character of the message.
.IP 0x03:
The payload specifies the priority of the message.
.IP 0x04:
The payload specifies the category of the message.
.IP 0x10:
This is a request for the state of the grid.  The payload is irrelevant.
.IP 0x11:
This writes to the grid.  The payload is a half-nybble for the X position on the grid, a half-nybble for the Y position on the grid, and a bit that is true for black or false for white.
.IP 0x80:
Your read or write to the grid has failed.  The payload is irrelevant.
.IP 0x81:
Your read succeeded.  The payload is the top half of the grid.
.IP 0x82:
See above, but for the bottom half of the grid.
.IP 0x83:
Your write succeeded.  The payload is 1 if it changed anything, or 0 if it didn't.
.SH SEE ALSO
.B gake(6)
